#!/usr/bin/perl

%outlibs = ("5211", "http://linkresolver.tamu.edu:9003/tamu?sid=Entrez:PubMed&id=pmid:", #"TAMU", 5705863
				 	  "1089", "http://nihlibrarysfx.nih.gov:9003/sfx_local?sid=Entrez:PubMed&id=pmid:", #"NIH_LIB",3874202
						"3538", "http://sfx.umd.edu/hs?sid=Entrez:PubMed&id=pmid:", #"UMD Health School",6319013
						"2967", "http://elinks.library.upenn.edu/sfx_local?sid=Entrez:PubMed&id=pmid:", #"UPENN",1339056
						"7251", "http://ucelinks.cdlib.org:8888/sfx_local?sid=Entrez:PubMed&id=pmid:", #"UCalifornia",7944284
						"6454", "http://infolink.lib.uiowa.edu/sfx_local?sid=Entrez:PubMed&id=pmid:", # "UIowa"8549553
						"9063", "http://foyer.swmed.edu/login?url=http://linksource.ebsco.com/?sid=Entrez:PubMed&id=pmid:", # "UT Southwestern"1768397
						"3001", "http://www.tdnet.com/unmc/resolver/default.asp?sid=Entrez:PubMed&id=pmid:", # "U Nebraska"6173724
						"1999", "http://sfx.stanford.edu/local?sid=Entrez:PubMed&id=pmid:", # "Stanford"5580936	
						"5673", "http://dy3uq8jh2v.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # UC-Denver,8066811
						"9158", "https://proxy.medlib.iupui.edu/login?url=http://www.ncbi.nlm.nih.gov/sites/entrez?holding=iusomlib&term=", #Indiana U - iusomlib,8845292
						"4590", "http://gn2ra8me3e.search.serialssolutions.com/OpenURL_local?sid=Entrez:PubMed&id=pmid:", # "Louisiana SU -Shreveport",3299750
						"9448", "http://tulink.library.tulane.edu:3210/sfx_local?sid=Entrez:PubMed&id=pmid:", # "Tulane",7697594
						"3303", "http://linksource.ebsco.com/linking.aspx?ID=1277&sid=Entrez:PubMed&id=pmid:", # "U Botswana",3198348
						"1796", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=tuhslib&term=", # "Tufts U",7011473 
						#"1465", "http://sfx.lib.duke.edu:9003/sfx_local?sid=Entrez:PubMed&id=pmid:", # "Duke",1437693
						#"1465", "http://proxy.lib.duke.edu/login?url=http://PM6MT7VG3J.search.serialssolutions.com/OpenURL_local?sid=Entrez:PubMed&id=pmid:", # "Duke",1437693
						"1465", "http://www.ncbi.nlm.nih.gov/pubmed?myncbishare=dukemlib&dr=abstract&holding=dukemlib_fft_ndi&otool=dukemlib&term=", # "Duke",1437693
						"4276", "http://openurl.library.uiuc.edu/sfxlcl3?sid=Entrez:PubMed&id=pmid:", # "UIUC",3800132
						#"8102440", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=wfusmlib&term=" # "Wake Forest"
						"8102440", "http://uv7gq6an4y.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Wake Forest"
						"2955041", "http://sfx.galib.uga.edu/sfx_emu1?sid=Entrez:PubMed&id=pmid:", #"Emory U"
						"8028940", "https://innopac.lsuhsc.edu/validate?url=http://linksource.ebsco.com/?sid=Entrez:PubMed&id=pmid:", # "Louisiana SU"
						"5438648", "http://df9uh2wc8b.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Florida International U"
						"5170456", "https://nexus.harding.edu/login?url=http://linksource.ebsco.com/?sid=Entrez:PubMed&id=pmid:", # "Harding U"
 						"7078927", "http://openurl.lib.rochester.edu/OpenURL_local?sid=Entrez:PubMed&id=pmid:", #"U Rochester"
						"9203674", "http://ns5hq7zn5a.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", #"Mount Sinai"
						"8871259", "http://sfx.exlibrisgroup.com:9003/calgary?sid=Entrez:PubMed&id=pmid:", #"U Calgary"
						"9001107", "http://sfxhosted.exlibrisgroup.com/duquesne?&rft_id=info:pmid/", #"Duquesne U"
						"4248424", "http://fa7pn9ym8k.search.serialssolutions.com/?pmid=", #"Thomas Jefferson U"
						"6251384", "http://bd4uz2kj6y.search.serialssolutions.com/OpenURL_local?sid=Entrez:PubMed&id=pmid:", #"U Arkansas M School"
						"1652031", "http://sfx.umdnj.edu:3210/sfxlcl3?sid=Entrez:PubMed&id=pmid:", #"U Medicine and Dentistry New Jersey"
						"4752561", "http://RY2UE4EK7D.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", #"Dartmouth"
						"6622249", "http://vx9bm7qu9a.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", #"Fox Chase Cancer Center"
						"2519804", "http://lib6.wsulibs.wsu.edu:8888/sfx_local?sid=Entrez:PubMed&id=pmid:", # "Washingston State U"
						"5377215", "http://ezproxy.pcom.edu:2048/login?url=http://linksource.ebsco.com/linking.aspx?sid=Entrez:PubMed&id=pmid:", # "Philadelphia College of Osteopathic Medicine"
						"9035897", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=tmalib&term=", #"Texas Medical Association"
						"8758667", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=flnfllib&term=", # "Nemours Foundation Libraries"
						"9269504", "http://1hsls.iii.com:4550/resserv?sid=Entrez:PubMed&pmid=", # "U Pittsburgh"
						"3962959", "http://ns2fr9hr7j.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "NY College of Osteopathic Medicine"
						"2040277", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=kmclib&term=", # "Kootenai Medical Center"
						"5366687", "http://ga6zr9ch7u.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Anderson Cancer Center"
						"1926518", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=mghlib&term=", # "Mass General Hospital"
						"9517528", "http://vd4zr3by2f.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "SUNY - Stony Brook"
				 	  "2858588", "http://findit.library.jhu.edu/resolve?sid=Entrez:PubMed&id=pmid:", # "Johns Hopkins University" 
				 	  "3471075", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=icacpbclib&term=", # "College of Physicians and Surgeons of BC Library"
				 	  #"9552186", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=nytoharlib_fft&term=", # "Touro-Harlem Medical Library"
						"9552186", "http://jc5yk5hu6q.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Touro-Harlem Medical Library"
						"7415170", "http://grlinker.coalliance.org/grlinker/grl000110/grl-TTU.cgi?sid=Entrez:PubMed&id=pmid:", # "TTUHSC Preston Smith Library"	
						"9005539", "http://ql3dq7xx6q.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "University of Washington"
					  "4685528", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=orugyklib&term=", # "Oregon College of Oriental Medicine", "orugyklib"
						"9700615", "http://resolver.ebscohost.com/openurl?sid=Entrez:PubMed&id=pmid:", # "Samuel Merritt University Library"
						"9599080", "http://rl3kp6xu8s.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "U of North Texas Health Science Center"
						"2276373", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=ctubridlib&term=", # "U of Bridgeport", "ctubridlib"
						"6700036", "http://DY7SQ4PE6F.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "SUNY College of Optometry", "sunyoptlib"
						"8993071", "http://DD8GH5YX7K.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "U of Sydney"
						"1918619", "http://sfx.med.nyu.edu/sfxlcl3?sid=Entrez:PubMed&id=pmid:", # "NYU"
						"7505226", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=mducfrlib&term=", # "NCI-Frederick", "mducfrlib"
						"1430570", "http://uthscsa.1cate.com/OpenURL_local?sid=Entrez:PubMed&id=pmid:", # "U Texas HSC, San Antonio"
						"3153070", "http://www.ncbi.nlm.nih.gov/sites/entrez?dr=citation&myncbishare=dhs&holding=casmphlib_fft&term=", # "State of Califorinia group", "casmphlib_fft"
						"8209024", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=caosjhlib&term=", # "Burlew Medical Library", "caosjhlib"
						"7009423", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=uvmdmlib&term=", # "University of Vermont", "uvmdmlib"
						"2820986", "http://ca3cx5qj7w.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Texas Medical Center"
						"6490522", "http://grlinker.coalliance.org/grlinker/grl000122/grl-PML.cgi?sid=Entrez:PubMed&id=pmid:", # "U Tennessee MC"
						"3070999", "http://sfx.uky.edu:3210/sfxlcl3?sid=Entrez:PubMed&id=pmid:", # "U Kentucky MC"
						"1892037", "http://sfx.carli.illinois.edu/sfxeiu?sid=Entrez:PubMed&id=pmid:", # "Eastern Illinois U"
						"8546138", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=mouslplib_fft_ndi&term=", # "St. Louis Pharmacy",  "mouslplib_fft_ndi"
						"1065610", "http://getit.lib.ksu.edu/sfxlcl3?sid=Entrez:PubMed&id=pmid:", # "Kansas State U"
						"1173294", "http://gz3hw6yy2n.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "NY Medical College"
						"8808621", "http://linksource.ebsco.com/linking.aspx?sid=Entrez:PubMed&id=pmid:", # "Mercer School"
						"6068796", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=gamorelib&term=", # "Morehouse School", "gamorelib"
						"1981861", "http://sfx.galib.uga.edu/sfx_med1?sid=Entrez:PubMed&id=pmid:", #, "Georgia Health Sciences Univ"
						"6455856", "http://elibrary.einstein.yu.edu/login?url=http://www.ncbi.nlm.nih.gov/sites/entrez?holding=yuaemlib&term=", # "Albert Einstein College", "yuaemlib"
						"6037714", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=fluzeilib&term=", # "Lee Memorial Health System", "fluzeilib"
						"9603856", "http://linkserv.lib.utk.edu:9003/sfx?sid=Entrez:PubMed&id=pmid:", # "U Tennessee"
						"2432757", "http://sfx.library.vcu.edu/vcu?sid=Entrez:PubMed&id=pmid:", # "Virginia C U"
						#"7198272", "http://getit.libraries.psu.edu:9003/sfx_local?sid=Entrez:PubMed&id=pmid:", # "Penn State U"
						"7198272", "http://sk8es4mc2l.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Penn State U"						
						"8285906", "http://sfx.usask.ca:9003/usask?sid=Entrez:PubMed&id=pmid:", # "U Saskatchewan"
						#"6635501", "http://www.tdnet.com/uscc/resolver/default.asp?sid=Entrez:PubMed&id=pmid:", # "U South Carolina"
						"6635501", "http://resolver.ebscohost.com/openurl?sid=Entrez:PubMed&id=pmid:", # "U South Carolina"
						"3652567", "http://qw8yt4sn4g.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "U South Alabama"
						"1934399", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=memclib&term=", # "Maine Medical Center", "memclib"
						"9290008", "http://www-fr.redi-bw.de/links/?rl_site=unihdma&sid=Entrez:PubMed&id=pmid:", # "U Heidelberg De"
						"1444522", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=florhslib&term=", # "Orlando Health", "florhslib"
						"1263487", "http://XK3ZD8EN7C.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Quinnipiac U"
						"1038874", "http://sfx.hul.harvard.edu/sfx_bypass/sfx_bypass.cgi?sid=Entrez:pubmed&id=pmid:", # "Harvard U"
						"5813325", "http://gettext.whoi.edu/sfxlcl41?sid=Entrez:PubMed&id=pmid:", # "Marine Bio Lab & Woods Hole"
						"1281698", "http://sfx.unimaas.nl:9003/sfx_local?sid=Entrez:PubMed&id=pmid:", # "Maastricht U"
						"5514834", "http://sfx.nlm.nih.gov/sfxnlmp41?&rft_id=info%3Apmid%2F", # "NLM Reading Room"
						"1447981", "http://vb3lk7eb4t.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "U North Carolina-Chapel Hill"
						"6173090", "http://rf9xu5rz6p.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Fred Hutchinson Cancer Research Center"
						"7276500", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=pauwkalib&term=", # "Wilkes University", "pauwkalib"						
						#"4721474", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=cuwmclib&term=", # "Cornell Medical Center"
						#"4721474", "http://sfxhosted.exlibrisgroup.com/cmc?sid=Entrez:PubMed&id=pmid:", # "Cornell Medical Center"
						"4721474", "https://weillcornell-primo.hosted.exlibrisgroup.com/openurl/01WCMC/WCMC?sid=Entrez:PubMed&id=pmid:", # "Cornell Medical Center"
						"3162066", "http://resolver.library.cornell.edu/net/openurl/?sid=Entrez:PubMed&id=pmid:", # "Cornell University"
						"8951502", "http://sfxhosted.exlibrisgroup.com/pnnl?sid=Entrez:PubMed&id=pmid:", # "Pacific Northwest National Laboratory"
						"2890566", "http://www.ncbi.nlm.nih.gov/sites/entrez?myncbishare=ACCLibraries&holding=txauscclib_fft&term=", # "Austin Community College", "txauscclib"
						"7786160", "http://px7gv7gt2n.search.serialssolutions.com/?V=1.0&pmid=", # "U New Mexico"
						"3833756", "http://hz9pj6fe4t.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "University of Illinois - Chicago"
						"1304674", "http://sfxhosted.exlibrisgroup.com/hfhs?sid=Entrez:PubMed&id=pmid:", # "Henry Ford Hospital"
						"8074896", "http://olinks.ohiolink.edu/olinks.php?sid=Entrez:PubMed&id=pmid:", # "U Akron"
						"1442648", "http://su2mq5jz6v.search.serialssolutions.com/?V=1.0&pmid=", # "Western Health, Australia"
						"4990378", "http://ld6wa5km9y.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Washington DC VA Medical Center"
						"7220495", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=canmcslib&term=", # "Natividad Medical Center", "canmcslib"
						"8872388", "http://ud4cl8nx8h.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Oklahoma State U"
						"6105212", "http://www.ncbi.nlm.nih.gov/sites/entrez?&term=", # "DUOC"
						"6759312", "http://nj3lt8sq3c.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "Bedford VAMC"
						"9896448", "http://olinks.ohiolink.edu/olinks.php?sid=Entrez:PubMed&id=pmid:", # "Summa Health System"
						"2906151", "http://zb5lh7ed7a.search.serialssolutions.com/uschsl?sid=Entrez:PubMed&id=pmid:", # "Univ of Southern California"
						"6586302", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=scvhlib&term=", # "Santa Clara VAlley Health & Hospital System", "scvhlib"
						"5724710", "http://linksource.ebsco.com.proxy.lib.mcw.edu/linking.aspx?sid=Entrez:PubMed&id=pmid:", # "Medical College of Wisconsin"
						"6211253", "http://sfxhosted.exlibrisgroup.com/burnham?sid=Entrez:PubMed&id=pmid:", # "Sanford-Burnham Medical Research Institute"
						"6646120", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=miuokwlib&term=", # "Oakwood Hospital & Medical Center", "miuokwlib"
						"3301831", "http://resolver.library.ualberta.ca/resolver?sid=Entrez:PubMed&id=pmid:", # "University of Alberta"
						"6254078", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=orusahlib&term=", # "Salem Hospital Community Health Education Center", "orusahlib"
						"4047552", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=waulzclib&term=", # "Pacific Northwest University of Health Sciences", "waulzclib"
						# "7015308", "http://p4550-catalogs.ohsu.edu.liboff.ohsu.edu/resserv?sid=pubmed&genre=article&id=pmid%3Apmid%3A", # "Oregon Health & Science University Library"
						"7015308", "http://librarysearch.ohsu.edu/openurl/OHSU/ohsu_services_page?sid=Entrez:PubMed&id=pmid:", # "Oregon Health & Science University Library"
						"5985634", "http://libsys.ewu.edu:4550/resserv?sid=Entrez:PubMed&id=pmid:", # "Eastern Washington University"
						"7863887", "http://healthwa.exlibris.com.au:3210/pmh?sid=Entrez:PubMed&id=pmid:", # "Princess Margaret Hospital, Western Australia"
						#"2005915", "http://healthwa.exlibris.com.au/smhs?sid=Entrez:PubMed&id=pmid:", # "Fremantle Hospital and Health Service, Western Australia"
						"2005915", "https://findit.health.wa.gov.au/smhs?sid=Entrez:PubMed&id=pmid:", # "Fremantle Hospital and Health Service, Western Australia"						 
						"6106801", "http://healthwa.exlibris.com.au:3210/rph?sid=Entrez:PubMed&id=pmid:", # "Royal Perth Hospital, Australia"
						"2938765", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=cabuclib&term=", # "Bastyr University - California", "cabuclib"
						"4883997", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=wabaulib&term=", # "Bastyr University", "wabaulib"
						"8612272", "http://ezproxy.acomedu.org/login?url=http://linksource.ebsco.com/linking.aspx?sid=Entrez:PubMed&id=pmid:", # "Alabama College of Osteopathic Medicine" 
						"6198267", "http://sfx.wisconsin.edu/wisc?sid=Entrez:PubMed&id=pmid:", # "University of Wisconsin - Madison"
						"9862780", "http://www.ncbi.nlm.nih.gov/sites/entrez?holding=ohjmilib&term=", # "Jeghers Medical Index"
						"7718779", "http://pc8ga3qq6a.search.serialssolutions.com/?sid=Entrez:PubMed&id=pmid:", # "University of Missouri – Kansas City Libraries"
						"7811789", "http://0-resolver.ebscohost.com.carlson.utoledo.edu/openurl?sid=Entrez:PubMed&id=pmid:" #, "University of Toledo Libraries"
					 );
	
